config/routes.rb
NationalParks::Application.routes.draw do  resources :parks
  resources :microposts
  get 'profiles/:id' => 'users#show', as: 'profiles'
  get "parks/index"
  devise_for :users
  root :to => "parks#index"
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :park
  validates_presence_of :content
  #validates_presence_of :tag
  validates_presence_of :user
  validates_presence_of :park
  #validates :park_id, presence: true
end

app/models/park.rb
class Park < ActiveRecord::Base
  validates_presence_of :parkname
  validates_presence_of :location
  validates_presence_of :info
  has_many :microposts
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_park
  private
  def current_park
    @current_park ||= Park.find(session[:last_park]) if session[:last_park]
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)
    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render action: 'show', status: :created, location: @micropost }
      else
        format.html { render action: 'new' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content).merge(park: current_park, user: current_user, tag: params[:tag])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :set_park, only: [:show, :edit, :update, :destroy]

  # GET /parks
  # GET /parks.json
  def index
    @parks = Park.all
  end

  # GET /parks/1
  # GET /parks/1.json
  def show
    if(params[:name] != nil)
      @park = find_by_name(params[:name])
    end
    @microposts = Micropost.find_all_by_park_id(@park.id)
    session[:last_park] = @park.id
  end

  # GET /parks/new
  def new
    @park = Park.new
  end

  # GET /parks/1/edit
  def edit
  end

  # POST /parks
  # POST /parks.json
  def create
    @park = Park.new(park_params)

    respond_to do |format|
      if @park.save
        format.html { redirect_to @park, notice: 'Park was successfully created.' }
        format.json { render action: 'show', status: :created, location: @park }
      else
        format.html { render action: 'new' }
        format.json { render json: @park.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parks/1
  # PATCH/PUT /parks/1.json
  def update
    respond_to do |format|
      if @park.update(park_params)
        format.html { redirect_to @park, notice: 'Park was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @park.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parks/1
  # DELETE /parks/1.json
  def destroy
    @park.destroy
    respond_to do |format|
      format.html { redirect_to parks_url }
      format.json { head :no_content }
    end
  end

  def find_by_name(parkname)
    Park.all.each do |park|
      if(park.parkname == parkname)
        return park
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_park
      @park = Park.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def park_params
      params.require(:park).permit(:parkname, :location, :info)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
    if(@user == current_user)
      if(params[:add_to_visited_parks] != nil)
        add
      elsif(params[:remove_from_visited_parks] != nil)
        remove
      end
    end
  end

  def add
    already_added = false
    if(@user.visited_parks == nil)
      @user.visited_parks = ''
    end
    @user.visited_parks.split("; ").each do |park|
      if(park == params[:add_to_visited_parks])
        already_added = true
      end
    end
    if(!already_added)
      if(@user.visited_parks == '')
        @user.visited_parks += (params[:add_to_visited_parks])
      else
        @user.visited_parks += ("; " + params[:add_to_visited_parks])
      end
    @user.save
    end
  end

  def remove
    temp_string = ''
    if(@user.visited_parks == nil)
      return
    end
    @user.visited_parks.split("; ").each do |park|
      if(park != params[:remove_from_visited_parks])
        if(temp_string == '')
          temp_string += park
        else
          temp_string += "; " + park
        end        
      end
    end
    @user.visited_parks = temp_string
    @user.save
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
	def avatar_url(park)
    name_id = park.parkname.gsub(/\s+/, "").downcase
    "http://intangiblefire.files.wordpress.com/2014/05/#{name_id}5.jpg?w=1100"
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %p App created by Alice, Sam, and Sarah
  %nav
    %ul
      /%li= link_to "About",   "#"
      /%li= link_to "Contact", "#"
      /%li
      /%a{href: "http://news.railstutorial.org/"} News

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "National Park Guide", "/", id: "logo"
      %nav
        %ul.navbar-text.pull-right
          /%li= link_to "Home",    '#'
          /%li= link_to "Help",    '#'
          /%li= link_to "Sign in", '#'

          - if user_signed_in?
            Logged in as
            = succeed "." do
              %strong= current_user.email
            = link_to 'View profile', profiles_path(current_user.id), :class => 'navbar-link'
            |
            = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
            |
            \#{link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
          - else
            = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
            |
            \#{link_to "Login", new_user_session_path, :class => 'navbar-link'}

app/views/layouts/_shim.html.haml
/[if lt IE 9] 
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title NationalParks
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    - if notice
      %p.alert.alert-success= notice
    - if alert
      %p.alert.alert-danger= alert
    = yield
    .container
      = render 'layouts/footer'

app/views/microposts/_form.html.haml
= form_for @micropost do |f|
  - if @micropost.errors.any?
    #error_explanation
      %h2= "#{pluralize(@micropost.errors.count, "error")} prohibited this micropost from being saved:"
      %ul
        - @micropost.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_field :content
  .field
    = radio_button_tag(:tag, "Weather")
    = label_tag(:tag, "Weather")
    = radio_button_tag(:tag, "Camping")
    = label_tag(:tag, "Camping")
    = radio_button_tag(:tag, "Hiking")
    = label_tag(:tag, "Hiking")
    = radio_button_tag(:tag, "Traffic")
    = label_tag(:tag, "Traffic")
  .actions
    = f.submit 'Save'

app/views/microposts/edit.html.haml
%h1 Editing micropost

= render 'form'

= link_to 'Show', @micropost
\|
= link_to 'Back', microposts_path

app/views/microposts/index.html.haml
%h1 Listing microposts

%table
  %tr
    %th Content
    %th Park
    %th User
    %th
    %th
    %th

  - @microposts.each do |micropost|
    %tr
      %td= micropost.content
      %td= micropost.park_id
      %td= micropost.user
      %td= link_to 'Show', micropost
      %td= link_to 'Edit', edit_micropost_path(micropost)
      %td= link_to 'Destroy', micropost, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Micropost', new_micropost_path

app/views/microposts/new.html.haml
%h1 New micropost

= render 'form'

= link_to 'Back', park_path(session[:last_park])

app/views/microposts/show.html.haml
%p
  %b Content:
  = @micropost.content
%p
  %b Tag:
  = @micropost.tag
%p
= link_to 'Edit', edit_micropost_path(@micropost)
\|
= link_to 'Back', park_path(session[:last_park])

app/views/pages/index.html.haml
%h1 National Parks

%table#parks
  %thead
    - @parks.each do |park|
      %tr
        %td= park.parkname
        %td= park.location
        %td= link_to "More about #{park.parkname}", park_path(park)
= link_to 'Add new national park', new_park_path

app/views/parks/_form.html.haml
= form_for @park do |f|
  - if @park.errors.any?
    #error_explanation
      %h2= "#{pluralize(@park.errors.count, "error")} prohibited this park from being saved:"
      %ul
        - @park.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :parkname
    = f.text_field :parkname
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :info
    = f.text_field :info
  .actions
    = f.submit 'Save'

app/views/parks/edit.html.haml
%h1 Editing park

= render 'form'

= link_to 'Show', @park
\|
= link_to 'Back', parks_path

app/views/parks/index.html.haml
%h1 Listing parks

%table#parks
  %thread
    %tr
      %th Parkname
      %th Location
      %th Info
      %th User Posts
     
  %tbody
    - @parks.each do |park|
      %tr
        %td= park.parkname
        %td= park.location
        %td= link_to "More about #{park.parkname}", park_path(park)
        %td= link_to "User posts for #{park.parkname}",park_path(park)
        / %td= link_to 'Show', park
        / %td= link_to 'Edit', edit_park_path(park)
        / %td= link_to 'Destroy', park, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

/= link_to 'Add New Park', new_park_path

app/views/parks/new.html.haml
%h1 New park

= render 'form'

= link_to 'Back', parks_path

app/views/parks/show.html.haml
%p#notice= notice

%ul#parkheading
 %li
  %b Parkname:
  = @park.parkname
 %li
  %b Location:
  = @park.location
%ul#lines
%ul#parkdetails
 %li
  %b Info:
  = @park.info

%br

%ul#links
 = link_to 'Edit', edit_park_path(@park)
 \|
 = link_to 'Back', parks_path
 \|
 - if user_signed_in?
  = link_to 'Add to visited parks', profiles_path(:id => current_user.id, :add_to_visited_parks => @park.parkname + ": " + @park.location)
 - else
  = link_to 'Add to visited parks', new_user_registration_path
 \|
 - if user_signed_in?
  = link_to 'Remove from visited parks', profiles_path(:id => current_user.id, :remove_from_visited_parks => @park.parkname + ": " + @park.location)
 - else
  = link_to 'Remove from visited parks ', new_user_registration_path
  

%ul#lines
 %h3#posttitle
  Microposts
%table#microposts
 %thead
  %tr
   %th Content
   %th User
   %th Tag
 %tbody
  - @microposts.reverse.each do |post|
   - username = User.find(post.user).email.split("@")[0]
   %tr
    %td= post.content
    %td= link_to username, profiles_path(User.find(post.user))
    %td= post.tag
%ul#lines

%ul#newpost
 = link_to 'Add new post', new_micropost_path, id: "newPost"

%ul#lines
 %h3#posttitle Map
 %ul#lines
 %td#img 
 = image_tag avatar_url(@park), :align => "middle"

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.haml
%h1 Profile of #{@user.email.split("@")[0]}

%ul#details
  %li
    Username:
    = @user.email.split("@")[0]

%h3 Parks Visited:
%table#visited_parks
  %thead
    %tr
      %th Park Name: Location
  %tbody
    - if(@user.visited_parks != nil)
      - @user.visited_parks.split("; ").each do |park|
        - name = park.split(": ")
        %tr
          %td= link_to "#{park}", park_path(:name => name[0])